config:
  - changed-files:
      - any-glob-to-any-file: "*"
tooling:
  - changed-files:
      - any-glob-to-any-file: "tooling/**/*.*"
assets:
  - changed-files:
      - any-glob-to-any-file: "static/**/*.*"
tests:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**/*.spec.js"
          - "cypress/**/*"
package:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"
source:
  - changed-files:
      - any-glob-to-any-file: "src/**/*"
